import { type WorkbenchRepository, type StoredInstance, type StoredConfigBackup } from './storage.ts';
import type { WorkbenchAppDefinition, WorkbenchConfig, WorkbenchCreatorDefinition, WorkbenchCreationResult, WorkbenchInstance, WorkbenchPresentationKind, WorkbenchService, WorkbenchSnapshot, WorkbenchTemplateDefinition } from './types.ts';
export declare function cloneConfig(value: unknown): WorkbenchConfig;
export interface WorkbenchControllerOptions {
    repository?: WorkbenchRepository;
    navigationStorage?: Pick<Storage, 'getItem' | 'setItem'> | null;
    confirmDiscard?: () => boolean;
    teardownTimeoutMs?: number;
}
/** Durable transactions and activation-owned registries; no renderer lives in storage. */
export declare class WorkbenchController implements WorkbenchService {
    private readiness;
    private readonly ownsRepository;
    get ready(): Promise<void>;
    private readonly repository;
    private readonly navigationStorage?;
    private readonly confirmDiscard;
    private readonly apps;
    private readonly templates;
    private readonly creators;
    private state;
    private route;
    private readonly presentations;
    private readonly statuses;
    private readonly pending;
    private readonly dirty;
    private readonly listeners;
    private loading;
    private error;
    private generation;
    private active;
    private readonly tasks;
    private readonly teardownTimeoutMs;
    private disposal?;
    private refreshTail;
    private creation;
    private creationAbort?;
    private snapshot;
    private readonly unsubscribe;
    constructor(options?: WorkbenchControllerOptions);
    getSnapshot(): WorkbenchSnapshot;
    subscribe(listener: () => void): () => void;
    getApp(id: string): WorkbenchAppDefinition | undefined;
    getTemplate(id: string): WorkbenchTemplateDefinition | undefined;
    private track;
    private drain;
    private assertActive;
    private assertGeneration;
    private require;
    private fail;
    private refresh;
    private readAndPublish;
    private applyState;
    retry(): Promise<void>;
    private mutate;
    registerApp(definition: WorkbenchAppDefinition): () => Promise<void>;
    private ensureDefault;
    private newInstance;
    registerTemplate(definition: WorkbenchTemplateDefinition): () => void;
    registerCreator(definition: WorkbenchCreatorDefinition): () => Promise<void>;
    createInstance(appId: string, title?: string, config?: WorkbenchConfig): Promise<WorkbenchInstance>;
    private createCheckedInstance;
    startCreation(templateId: string): Promise<WorkbenchCreationResult>;
    cancelCreation(): void;
    prepareInstance(id: string): Promise<void>;
    renameInstance(id: string, title: string): Promise<void>;
    deleteInstance(id: string): Promise<void>;
    updateInstanceConfig(id: string, patch: WorkbenchConfig, expectedRevision?: number, generation?: number | undefined): Promise<number>;
    exportInstance(id: string): Promise<{
        instance: StoredInstance;
        backups: StoredConfigBackup[];
    }>;
    restoreBackup(id: string, backupRevision: number, expectedRevision: number): Promise<void>;
    reorderInstances(ids: readonly string[]): Promise<void>;
    setDirty(id: string, dirty: boolean): void;
    private navigate;
    open(id: string, presentation?: WorkbenchPresentationKind): void;
    openHome(creating?: boolean): void;
    openConversation(): void;
    close(): void;
    private publicInstance;
    private publish;
    dispose(): Promise<void>;
}
